name: Test PR

# Controls when the action will run.
on:
  # Triggers the workflow on PR to main 
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: go test -v -cover ./...

    - name: Test `go fmt && go generate` on Go 1.19 creates no diffs
      run: go fmt && go generate && git diff --exit-code

    - uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2022.1.3"
        install-go: false
